### ISSUE TITLE
Ability to query frame containing values for each channel

### ISSUE THREAD

**Issue by aruss175** [equinor/dlisio#105]
When getting the channels from a file - it would be helpful to know which frame the channel has its curve values in.  For example TDEP (depth curve) can be in multiple frames with different sampling rates.  The problem is that I don't know which TDEP long description from channel.long_name matches which TDEP in the numpy array.  I can't match on name (names are identical) so do you parse in a specific order so I can at least sort it out by giving the channel an index which matches the reading order of the frames?

![image](https://user-images.githubusercontent.com/43067386/57444683-faab6f00-7250-11e9-85be-316941317b2a.png)

**Comment by ErlendHaa** [comment]
Hi!

If I understand you correctly, this is already been fixed in version 0.1.6:
If all curve mnemonics are unique, then `dtype.names` == [ch.name for ch in `self.channels]`. If there are more than one channel with the same name for this frame, all duplicated mnemonics are enriched with origin                and copynumber. You can even customize the mnemonic by setting the instance spesific `frame.dtype_fmt` attribute or `frame.dtype_format` (default for all frames). See https://dlisio.readthedocs.io/en/stable/dlisio.html#frame

Regarding the curve order in the frame array: The order is the same as in the channels attribute. I.e. the order of `dtype.name` is equal to `frame.channels`

**Comment by aruss175** [comment]
Thank Erlend, the situation is when you have duplicate mnemonics in different frames.  The example above has one TDEP in frame 1 and another TDEP in frame 2.  So I need to confirm that DLISIO reads frame 1 first, so then the first TDEP in `for channel in self.channels` is from frame 1, and the second TDEP in `for channel in self.channels` is from frame 2.

**Comment by ErlendHaa** [comment]
Hi!

I see! First a quick note on the ordering:  `f.frames` and `f.channels` is **not** ordered! However, the `frame.channels` is.

Channel is not linked to its parent frame (because a channel can be reused in different frames). This means you have to go through the frame object to identify the channels in that frame. There should probably be an easy opt in to use the extended mnemonics for all labels, regardsless of duplication or not. Name, origin and copynumber in the mnemonics gives sufficient information to create a fingerprint and locating the channel. But for now you can manually patch all names in the curve doing something like this:

```
with dlisio.load(filepath) as f:
    for frame in f.frames:
        fp  = frame.fingerprint
        curves  = f.curves(fp)

        mnemonics = []
        for channel in frame.channels: 
           mn = ':'.join([channel.name, str(channel.origin), str(channel.copynumber)])
           mnemonics.append(mn)
 
        curves.dtype.names = mnemonics
```
Then you'll have enough information to deduce which channel it is. Or you can just use the same ` for channel in frame.channels` to access the correct TDEP channel.

**Comment by ErlendHaa** [comment]
But yes, this entire interface needs an overhaul

**Comment by ErlendHaa** [comment]
With the introduction of back-reference the parent frame from channels (#136), I'll consider this issue to be resolved.
