### ISSUE TITLE
Invalid format specifier 

### ISSUE THREAD

**Issue by jhalotel** [equinor/dlisio#122]
Not implemented yet: invalid format specifier in fSSSSffffffffffSSSSfffffffff

**Comment by achaikou** [comment]
None of the files I've got failed with this message, but if the error isn't caused by any other reason (looks like could have happened because of logical files issue), then we have fdata recorded as S (ASCII).

Reading ASCII fdata right now is not supported, but looks like there are real files out there requesting it.

**Comment by jokva** [comment]
Variable-length data types are supported since https://github.com/equinor/dlisio/releases/tag/v0.1.14
