### ISSUE TITLE
Multiple frames in one FDATA

### ISSUE THREAD

**Issue by jhalotel** [equinor/dlisio#123]
Not implemented yet: multiple frames in one FDATA

**Comment by achaikou** [comment]
When reading curves in Suite***Cust.DLIS would get one of 2 possible errors:

If we encounter frame 10B first:
Not implemented yet: multiple frames in one FDATA

or
If we encounter frame 15B first:
RuntimeError: unaligned record: tail (which is 10984) < fmt_size (which is 27976)

We also get a lot of information about
"ERROR multiple distinct objects in set" and "WARNING  missing attribute 'channels' dlisio.core.obname"

Warnings and errors might have been expected for release prior to 0.1.11, but this one already contains Logical Files support.
So it looks like there is a bug somewhere in Logical Files solution.

4 LF files are created, but first 2 are empty and most of the explicit data is visible in 2 remaining files.
Tracking down issue in 15B file shows en example that something is wrong:
In every logical file there is a channel named U001 with exact same origin and copy number. In the first 3 Logical Files dimension of this channel is 120. In the 4th one - 356.
Then it looks like we read fdata belonging to some of the first 3 logical files, but channel.dimension shows dimension to be 356. Hence DLISIO predicts bigger data size than is there.

When divided file into 4 separate files, curves in all 4 were read correctly, which confirms that something is wrong with logical files support.

**Comment by achaikou** [comment]
Looks like the issue is in misalignment between records and ex[pl]i[cits] in find_fileheaders function. When extracting records, 'core -> extract' ignores encrypted records and doesn't store them. 'exi', on the other side, counts all the records.

If 'no-encrypted-records' restriction is lifted, all data seems to be read correctly, file doesn't fail anymore on loading curves and all the logical files look fine.
