### ISSUE TITLE
Consider adding the number of parameters to dlis.describe()

### ISSUE THREAD

**Issue by erlendviggen** [equinor/dlisio#230]
The `describe()` function of `dlis` objects currently prints the number of frames and channels in the logical file, but not the number of parameters. It's quite easy for the user to find this number as `len(file.parameters)`, but maybe it should also be printed in the overview? It's a tiny thing, but I thought I might mention it.

**Comment by ErlendHaa** [comment]
Hi

This feature got removed in 0.1.15 actually. It kind of a side-effect of an performance-improvement we introduced. Let me explain:

Pre 0.1.15, `dlisio.load()` parsed and loaded _every_ metadata object in the file. Doing so was one of the bottlenecks of load, especially for files with a high number of metadata objects. In 0.1.15, only Fileheader, Origin, Frame and Channel-objects are loaded by default. Other object-types are loaded when need, e.g. `len(f.parameter)` will load parameter object. 

Due to the way objects are structured in dlis-files, it is as expensive to just count them as it would be to parse them (i.e. do a full load). Hence if `dlis.describe()` with object-count for all objects would eat up all the performance gained in `dlisio.load`. 

A option might be to let `dlis.describe()` take an argument that specifies whether or not to count all objects.

**Comment by ErlendHaa** [comment]
On a second thought, if someone call `.describe()` it is reasonable to assume that they are not processing a large amount of dlis-files, but rather focuses on exploring a single (or a few) files. Hence, the performance gain is not that important anymore and we should probably prioritize convenience.

**Comment by ErlendHaa** [comment]
Brought this back in #235, its part of v0.1.16
