### ISSUE TITLE
Sample Python code for getting basic overview of DLIS file

### ISSUE THREAD

**Issue by debasisc-opa** [equinor/dlisio#293]
I have Python installed in my Windows desktop and can develop using IDLE. Looking for starting "Hello World" style code to open DLIS file and can get some basic information about parameters, list of curves. After that, I can gradually add codes to do more advanced tasks.

I have been checking for suitable file(s) in the following location, but not very sure which one is suitable.
https://github.com/equinor/dlisio/tree/master/python (folders like docs, dlisio, test)

Thanks in advance for your help.

Debasis

**Comment by ErlendHaa** [comment]
Hi

I highly recommend that you start by skimming through the official [documentation](https://dlisio.readthedocs.io/en/stable/index.html). There is also a notebook with some good examples on how to investigate a dlisio file that you might want to check out: https://github.com/equinor/dlisio-notebooks. You can play around with the notebook by launching binder

**Comment by debasisc-opa** [comment]
Thanks @ErlendHaa . 
I used Acoustic example to make up this code (copy/paste) and tried using the following file from Volve data set.
15_9-F-10-WLC_PETRO_COMPUTED_INPUT_1.DLIS
Result can be seen in PNG. The only thing I miss from the overview is depth interval.
Can you please check this and advise?
Thank you

![15_9-F-10-WLC-Petro_computed_input-Python-output](https://user-images.githubusercontent.com/65125182/92174663-ee620280-ee01-11ea-881c-3858d5d6dc4b.PNG)


[15_9-F-10-WLC-Petro_computed_input-Python-code.pdf](https://github.com/equinor/dlisio/files/5171188/15_9-F-10-WLC-Petro_computed_input-Python-code.pdf)



[15_9-F-10-Composite-Infoview.pdf](https://github.com/equinor/dlisio/files/5171175/15_9-F-10-Composite-Infoview.pdf)

**Comment by ErlendHaa** [comment]
Hi

First of all, issues are not a one to one conversation. They serve as a reference for further users that might run into the same thing. So I would appreciate it if you made one issues for each (unrelated) problem, rather than changing the current one.  Also it generally help's if you post the exact code that produced the problem. That saves me, and anyone else that might use this issue as a reference, some time. Preferably all code should be posted as text as well.

Anyway, this is the line that produces the output you are wondering about:

`print(f'Interval         : [{frame.index_min}, {frame.index_max}] {index_channel.units}')`

more specifically, `frame.index_min` and `frame.index_min` both returned `None`. The reason is that those fields are not recorded in the file. That is a general theme about dlis files. The dlis specification defines structures like a `frame`, however it does not enforce that all fields of a `frame` should be populated with data. That decision is left to the vendor. Hence some information is sometimes omitted. 

However, in this case you can figure out the interval (and direction) yourself. It's simply the first and the last value of the index channel.

```
curves = frame.curves()
# Assume for now that the first entry is the lower one. I.e. that the index is increasing
index_min = curves[frame.index][0]
index_max = curves[frame.index][-1]
direction = 'INCREASING'

# Check our assumption and swap it does not hold
if (index_min > index_max):
  index_min, index_max  = index_max, index_min
  direction = 'DECREASING'
```

**Comment by debasisc-opa** [comment]
Hi @ErlendHaa ,

Thank you for response.
A.
With your suggestion, I am able to print depth interval (minimum, maximum, direction).
However, as the output values are different from what I see from Schlumberger Log Data Toolbox, I would like to report the difference.
But as that is beyond the scope of "Hello World" example, I plan to enter a new issue asking that specific question.

B.
Including code as PDF - I'll keep your suggestion in mind for later. Simply copy/paste the code text in message.

Thank you

Debasis

**Comment by debasisc-opa** [comment]
@ErlendHaa - Do you think I should close this issue now, with suitable comment? Or leave that to you to 'close' by indicating that is is resolved successfully? Thank you

**Comment by ErlendHaa** [comment]
Great!

Your above comment, which confirms that we have found a suitable solution to the issue should suffice.
