### ISSUE TITLE
Performance regression in dlisio 0.2.5

### ISSUE THREAD

**Issue by eimerej** [equinor/dlisio#303]
Hi,
Since I updated from 0.2.4 to 0.2.5 I have a huge performance regression.
A file that I was able to parse in 9s now takes more than 1m30.

All the time seems to be is spent in pool::get function.

**Comment by ErlendHaa** [comment]
Hi,

Thanks for the feedback. Can you please share the code you run? I struggle to reproduce this large of a regression. From a quick profiling I see that a lot of time is spent in BasicObject.fingerprint, which is called in dlis.__getitem__ when constructing the returned dict. Removing the dict all-together leaves me with better performance than v0.2.4.

**Comment by eimerej** [comment]
Sorry, I didn't put enough details in my report.
You don't want to write such code but for demonstration purpose, the code below takes 1,2,3 seconds to run in 0.2.4 depending of the dlis size, now it can takes several minutes.

```py
def parse(file_name):
    with dlisio.load(file_name) as files:
        for logical_file in files:
            for channel in logical_file.channels:
                for tool in logical_file.tools:
                    if channel in tool.channels:
                        pass
```

I'll continue the investigation.
Thanks for  your help.

**Comment by ErlendHaa** [comment]
Hi again.

You are right in that the majority of time goes is spent querying objects. The problem here is not the pool.get itself, all though that too can be optimised a bit, but rather the share amount of repeated calls to it. 

In v0.2.4 we cached all metadata objects in python after the first query, in v0.2.5 we fetch objects from c++ for each query. The assumption was that repeated calls to the same objects were rather limited, hence the performance overhead was low. The patch had a positive impact on performance when this is the case. However, as your example code illustrates very well, it's rather easy to write some loops where the assumption doesn't hold at all. 

On a random file with 310 channels and 7 tools, the snippet below ends up with ~86800 (310 * 7 * 40) queries to  `logical_file.object()`,  which fetches objects from the c++ store with `pool.get`. That takes me 15 secs to run. On another file with zero tools the queries drop to around 310 and the code runs in no time.

```
def parse(file_name):
    with dlisio.load(file_name) as files:
        for logical_file in files:
            for channel in logical_file.channels:   # 310 channels
                for tool in logical_file.tools:     # 7 tool
                    if channel in tool.channels:    # Each tool has an average of 40 channels
                        pass
```

This is obviously not acceptable and a big blunder from us. While you wait on a fix from us, there is a couple of things you can do to get the performance back. If you need nested loops, caching the results from `logical_file.channels/tools` and `tool.channels` manually solves the problem. Or for this exact example the code can be re-arranged to avoid nested loops:
```
for logical_file in files:
    for channel in logical_file.channels:
       if not channel.source: continue
       if channel.source.type == 'TOOL':
           pass
```
For me that took the execution time down from 15s to <0.2s.

**Comment by ErlendHaa** [comment]
Hi,

After giving this some more thought I'm no longer so sure that this is an issue we need to fix in dlisio. I do agree that it's unexpected that this specific piece of code should perform so much worse on v0.2.5. And that is an unfortunate effect of dlisio no longer caching metadata in Python. 

However, the issue here boils down to the fact that the caller code queries the same objects over and over in the innermost loop - something that is easily avoidable, and something that should be avoided regardless of dlisio's implementation. Generally I would say that it's not dlisio's job to guard against these huge loops.

Caching of objects has its own set of problems too - leading us to remove it in the first place. I still consider that a positive change to the codebase, even if such worst-case scenarios can be constructed. I will consider adding memoization to the query functions on the logical files, which would help this particular code perform better. But mostly because there might be some more trivial user-patterns that might benefit from it.

**Comment by eimerej** [comment]
Hi @ErlendHaa,

Thanks for your help. I reviewed my code and now I've almost the same performance as 0.2.4 (still about 8% slower)
I found that it's not always obvious to know from the API which call will trigger the lookup.
