### ISSUE TITLE
Unable to find depth_reprc values in LIS79-specific types

### ISSUE THREAD

**Issue by zuzulacas** [equinor/dlisio#378]
Hello,
Thank you for the great job you are doing on this project.
I don't know if it is the best way to require some help but I am trying this way. 
On the lis parser, I am trying to get the index/depth curve name using the depth_reprc attribute (from the dfsr object) but I am unable to find the equivalent curve name in the lis-79.pdf file. Do you have a mapping for this attribute?
Thank you

**Comment by ErlendHaa** [comment]
Hi!

`depth_reprc` does not refer to the name/mnemonic of a curve. It refers to the data-type used to store the curve. It's an integer and it's value is defined by Appendix B in the [LIS79 spec](http://w3.energistics.org/LIS/lis-79.pdf). This is used internally to correctly parse the curves and set the right type in the numpy array produced by the `curves` function. 

If it's the name/mnemonic you are after, you have to look at the [Spec Blocks](https://dlisio.readthedocs.io/en/stable/lis/api.html#lis-structures). Note that LIS has 2 ways of recording the index of a DataFormatSpec. Which mode your file uses can be checked with [DataFormatSpec.depth_mode](https://dlisio.readthedocs.io/en/stable/lis/api.html#dlisio.lis.DataFormatSpec.depth_mode). If depth mode is 0, then the _first_ spec block in `DataFormatSpec.specs` defines the index - which stores both the mnemonic, units and other meta about the index. If depth mode is 1, then the index is _not_ described by a Spec Block and the name/mnemonic is implicitly 'TDEP' and the units are recorded in `DataFormatSpec.depth_units`.

As you see it's a bit cumbersome to deal with the index due to LIS79's different recording modes for the index. In the next version, which will be out soon, we add a couple of convince functions that makes it more straightforward to get the index name/mnemonic and units, without having to manually check the depth mode.

**Comment by zuzulacas** [comment]
Hi Erlend,

Thanks for the clear explanation, I will explore your logic to try to get the info. I will then need to extract the min and max for each curve index, which way should I go for it?

Should I close the issue or keep it open until I get what I am expecting?

Thanks again.

Thibault

**Comment by ErlendHaa** [comment]
Generally we like to keep one ticker pr issue. This makes it easier for others in the future to look for closed issues matching their issue before creating their own. 

Min/max is not explicitly recorded in LIS79 files. You would have to calculate statistics about the curves ourself. For min/max it would be the _first_ and _last_ sample of the index curve. (Assuming the index is always strictly increasing or decreasing). Which one is max and min depends on the direction of the log (see 1DataFormatSpec.direction`).

E.g. if the index is 'DEPT' direction is down-hole:

```
curves = lis.curves(f, fs)
index  = curves['DEPT']

min = index[0]
max = index[-1]
```

It's all numpy, so alternatively, you can use [numpy's min()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.min.html) and max():

```
min = index.min()
max = index.max()
```

**Comment by ErlendHaa** [comment]
As of 0.3.5 you can now use [index_mnem](https://dlisio.readthedocs.io/en/stable/lis/api.html#dlisio.lis.DataFormatSpec.index_mnem) and [index_units](https://dlisio.readthedocs.io/en/stable/lis/api.html#dlisio.lis.DataFormatSpec.index_units) without manually checking the `depth_mode`
