### ISSUE TITLE
Issues with Reading LIS Files...

### ISSUE THREAD

**Issue by nwshaw** [equinor/dlisio#384]
Hi DLISIO Team, 

I'm trying to read LIS files using the latest version of the DLISIO library, however every file I try its failing.  Below is a fragment of code I'm using.   Failing every time on _for format_spec in format_specs:,_ with the exception _'method' object is not iterable_

Any thoughts?

Thanks in advance

N.

 with lis.load(strFileName) as files:

            try:
                for f in files:
                    format_specs = f.data_format_specs
                    **for format_spec in format_specs:**
                        for sample_rate in format_spec.sample_rates():
                            data = lis.curves(f, format_spec, sample_rate)
                            meta = lis.curves_metadata(format_spec, sample_rate)

            except Exception as e:
                print(e)

**Comment by ErlendHaa** [comment]
Hi

The error is due to a syntax error in your code. [f.data_format_spec](https://dlisio.readthedocs.io/en/stable/lis/api.html#dlisio.lis.LogicalFile.data_format_specs) is method, like the error suggest. Your code should be:

```
for f in files:
    for format_spec in f.data_format_specs():
        for sample_rate in format_spec.sample_rates():
            data = lis.curves(f, format_spec, sample_rate)
            meta = lis.curves_metadata(format_spec, sample_rate)
  ```                      
  
  I see that this miss-understanding might originate from dlisio's [own documentation](https://dlisio.readthedocs.io/en/stable/lis/userguide.html#), which also gets this wrong. I will update the relevant sections

**Comment by nwshaw** [comment]
Thank You !!
