### ISSUE TITLE
Issue with installing from pip om M1 Mac

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/dlisio#421]
I have trouble installing dlisio with pip.
Other packages can be installed without any issues.

Steps to reproduce:
1) Create a new virtual environment with python version 3.9.1
2) upgrade pip to latest version with `python -m pip install --upgrade pip`
3) running the command `pip install dlisio` gives this error:
![image](https://user-images.githubusercontent.com/69512295/217281377-1b76b679-ddd5-4ed6-875f-452b5de709c5.png)

Also, pip index does not find any versions. The pip index command finds all verions other packages, like numpy
![image](https://user-images.githubusercontent.com/69512295/217281622-675b9bc8-86c9-4f54-bb37-67f4ed2b16aa.png)

Tried on Mac OS Ventura 13.1 (with M1 chip)

**Comment by KristianKjerstad** [comment]
also tried with python 3.8.12 and got same issue

**Comment by ErlendHaa** [comment]
Hi! Unfortuanally we don't provide any prebuilt python wheels for ARM on MacOS. The reason is that GitHub action, which is used to build and publish wheels, doesn't have any runners for arm and we haven't gotten cross-compilation to work properly.

dlisio does build fine on the new ARM machines tho, so you could compile it yourself. Alternatively you can enable rosetta in your terminal and install the prebuilt pip wheels for intel Macs.

**Comment by Northo** [comment]
@ErlendHaa, MacOS ARM runners were recently released into public beta: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions !!
The naming convention is a bit confusing, but the `macos-<version>-xlarge` runners should be on M1 (see [this](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners) for details).

Looking forward to M1 wheels!!

**Comment by achaikou** [comment]
MacOS ARM wheels should be available from dlisio 1.0.1.
